apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: caddy-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: caddy-ingress-controller
    repoURL: https://caddyserver.github.io/ingress
    targetRevision: "0.9.0"
    helm:
      values: |
        ingressController:
          config:
            email: CHANGE_ME_EMAIL
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: caddy-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
